// 100 wook-festival outfits for her, plus matching looks for him.
// Each `items` entry is both the display label and the search query.
// Amazon/SHEIN search URLs are generated at render time from the string.

export const HER_OUTFITS = [
  // ───────── DAYTIME (1–40) — hot sun, dust, closed-toe mandatory ─────────
  { id: 1, time: "day", name: "Canyon Wanderer", vibe: "Boho Warm", items: [
    "cream crochet bralette",
    "rust linen wide leg pants women",
    "cream wide brim felt hat",
    "bronze wire aviator sunglasses",
    "tan platform sneakers women",
    "layered gold coin necklace",
  ]},
  { id: 2, time: "day", name: "Desert Daisy", vibe: "Prairie", items: [
    "white crochet tank top women",
    "tan tiered mini skirt",
    "straw cowboy hat women",
    "turquoise pendant necklace",
    "tan ankle boots women",
  ]},
  { id: 3, time: "day", name: "Sunset Cowgirl", vibe: "Western", items: [
    "rust gingham crop top",
    "denim cutoff shorts high waist",
    "brown leather cowboy hat",
    "silver concho belt women",
    "brown western ankle boots",
  ]},
  { id: 4, time: "day", name: "Mesh Dreamer", vibe: "Street Boho", items: [
    "beige mesh knit crop tank",
    "olive cargo shorts women",
    "tan bucket hat",
    "tortoise wrap sunglasses",
    "white chunky sneakers women",
  ]},
  { id: 5, time: "day", name: "Lace & Linen", vibe: "Soft Boho", items: [
    "ivory lace crop cami",
    "cream linen wide leg pants",
    "raffia wide brim sun hat",
    "layered gold necklaces",
    "cream canvas sneakers",
  ]},
  { id: 6, time: "day", name: "Boho Warrior", vibe: "Edgy", items: [
    "rust halter crop top",
    "brown suede fringe shorts",
    "feather dangle earrings",
    "stacked silver rings",
    "brown ankle boots women",
  ]},
  { id: 7, time: "day", name: "Tribal Goddess", vibe: "Boho", items: [
    "bronze metallic bralette",
    "rust harem pants women",
    "gold coin belt",
    "gold cuff bracelet",
    "brown ankle boots",
  ]},
  { id: 8, time: "day", name: "Crochet Queen", vibe: "Knit Wook", items: [
    "cream crochet two piece set",
    "wide brim raffia hat",
    "gold coin layered necklace",
    "tan suede ankle boots",
  ]},
  { id: 9, time: "day", name: "Festival Fairy", vibe: "Pastel", items: [
    "pastel tie dye cropped tee",
    "white denim high waist shorts",
    "iridescent heart sunglasses",
    "gold glitter body chain",
    "white platform sneakers",
  ]},
  { id: 10, time: "day", name: "Earth Child", vibe: "Minimal Boho", items: [
    "rust ribbed tank top women",
    "olive wide leg cargo pants",
    "brown leather fanny pack",
    "gold hoop earrings",
    "brown chunky sneakers",
  ]},
  { id: 11, time: "day", name: "Woodstock Dream", vibe: "70s Hippie", items: [
    "peach tie dye tank top",
    "denim overall shorts women",
    "round john lennon sunglasses",
    "flower crown headband",
    "tan sneakers women",
  ]},
  { id: 12, time: "day", name: "Prairie Girl", vibe: "Cottagecore", items: [
    "cream crochet lace blouse",
    "denim midi skirt",
    "brown wide brim hat",
    "silver coin necklace",
    "brown boots women",
  ]},
  { id: 13, time: "day", name: "Sheer Lover", vibe: "Layered Day", items: [
    "sheer mesh long sleeve top cream",
    "high waist linen shorts beige",
    "floppy straw sun hat",
    "wire frame sunglasses",
    "cream sneakers women",
  ]},
  { id: 14, time: "day", name: "Terracotta Dream", vibe: "Warm Neutral", items: [
    "terracotta knit halter top",
    "tan flowy culottes",
    "straw bucket hat",
    "gold hoop earrings",
    "tan espadrille sneakers",
  ]},
  { id: 15, time: "day", name: "Festival Fringe", vibe: "70s Rock", items: [
    "cream suede fringe vest",
    "white ribbed tank top",
    "denim cutoff shorts",
    "brown fringe crossbody bag",
    "brown boots women",
  ]},
  { id: 16, time: "day", name: "Sun Goddess", vibe: "Metallic Day", items: [
    "gold metallic crop top",
    "cream linen wide leg pants",
    "gold statement earrings",
    "gold layered necklaces",
    "gold chunky sneakers women",
  ]},
  { id: 17, time: "day", name: "Wildflower", vibe: "Floral", items: [
    "floral wrap crop top",
    "tan tiered midi skirt",
    "wide brim straw hat",
    "silver bangle stack",
    "tan boots women",
  ]},
  { id: 18, time: "day", name: "Western Romance", vibe: "Cowgirl", items: [
    "white eyelet crop top",
    "denim maxi skirt with slit",
    "brown cowboy hat",
    "turquoise belt buckle",
    "western boots women",
  ]},
  { id: 19, time: "day", name: "Boho Edge", vibe: "Dark Boho", items: [
    "black mesh crop top",
    "olive cargo mini skirt",
    "black combat boots women",
    "layered chain chokers",
    "bandana headband",
  ]},
  { id: 20, time: "day", name: "Canyon Dust", vibe: "Sporty", items: [
    "oversized cream muscle tank",
    "rust bike shorts women",
    "cream baseball cap",
    "gold hoop earrings",
    "white sneakers",
  ]},
  { id: 21, time: "day", name: "Gypsy Rose", vibe: "Romantic", items: [
    "pink bohemian crop blouse",
    "tan culotte pants",
    "raffia tote bag",
    "gold body chain",
    "tan canvas shoes",
  ]},
  { id: 22, time: "day", name: "Hippie Chic", vibe: "Tie Dye", items: [
    "orange tie dye tank dress",
    "brown braided belt",
    "floppy sun hat",
    "beaded layered necklaces",
    "brown ankle boots",
  ]},
  { id: 23, time: "day", name: "Desert Nomad", vibe: "Utility", items: [
    "beige cropped button up shirt",
    "brown cargo shorts women",
    "safari hat",
    "aviator sunglasses",
    "tan hiking shoes women",
  ]},
  { id: 24, time: "day", name: "Festival Royalty", vibe: "Glam Day", items: [
    "gold sequin bralette",
    "cream flowy palazzo pants",
    "gold crown headpiece",
    "gold bangle bracelets",
    "gold sneakers women",
  ]},
  { id: 25, time: "day", name: "Lace Fairy", vibe: "Cottagecore", items: [
    "white lace babydoll crop top",
    "denim shorts women",
    "daisy hair clips pack",
    "pearl choker necklace",
    "white sneakers women",
  ]},
  { id: 26, time: "day", name: "Earth Angel", vibe: "Soft Neutral", items: [
    "ivory crochet bikini top",
    "beige linen maxi skirt",
    "wide brim straw hat",
    "gold anklet",
    "ivory sneakers",
  ]},
  { id: 27, time: "day", name: "Rust & Cream", vibe: "Warm Minimal", items: [
    "rust crop tee",
    "cream high waist linen shorts",
    "cream bucket hat",
    "gold layered chains",
    "white sneakers",
  ]},
  { id: 28, time: "day", name: "Woodstock '69", vibe: "Retro Hippie", items: [
    "rainbow tie dye tank top",
    "high waist bell bottom jeans",
    "round retro sunglasses",
    "flower headband",
    "white sneakers",
  ]},
  { id: 29, time: "day", name: "Dust Rider", vibe: "All Black", items: [
    "black mesh tank top",
    "black bike shorts",
    "black bucket hat",
    "silver chain necklaces",
    "black chunky boots",
  ]},
  { id: 30, time: "day", name: "Golden Child", vibe: "Sunny", items: [
    "yellow halter crop top",
    "white denim shorts",
    "straw sun hat",
    "gold pendant necklace",
    "white sneakers",
  ]},
  { id: 31, time: "day", name: "Festival Flow", vibe: "Flowy", items: [
    "beige halter mini dress with slit",
    "brown fringe belt",
    "floppy hat",
    "gold bangles",
    "tan ankle boots",
  ]},
  { id: 32, time: "day", name: "Bronze Beauty", vibe: "Warm Metallic", items: [
    "bronze crop tank top",
    "tan harem pants",
    "silver coin belt",
    "bronze hoop earrings",
    "brown sneakers",
  ]},
  { id: 33, time: "day", name: "Meadow Walker", vibe: "Sage", items: [
    "sage green crochet top",
    "white flowy shorts",
    "straw bucket hat",
    "gold necklace",
    "white sneakers",
  ]},
  { id: 34, time: "day", name: "Prairie Free", vibe: "Embroidered", items: [
    "white embroidered crop blouse",
    "denim shorts women",
    "brown cowboy hat",
    "turquoise squash blossom necklace",
    "brown boots",
  ]},
  { id: 35, time: "day", name: "Mirage", vibe: "Pastel Dust", items: [
    "pastel tie dye crop top",
    "white linen wide leg pants",
    "cream bucket hat",
    "gold hoop earrings",
    "white sneakers",
  ]},
  { id: 36, time: "day", name: "Sage & Stone", vibe: "Earthy", items: [
    "sage green ribbed tank top",
    "olive cargo pants women",
    "raffia wide brim hat",
    "gold stacking rings",
    "tan ankle boots",
  ]},
  { id: 37, time: "day", name: "Sunflower", vibe: "Floral Fun", items: [
    "yellow sunflower crop top",
    "denim mini skirt",
    "daisy headband",
    "gold pendant",
    "white sneakers",
  ]},
  { id: 38, time: "day", name: "Wild & Free", vibe: "Boho", items: [
    "rust mesh crop top",
    "brown cargo shorts",
    "wide brim boho hat",
    "brown fringe crossbody",
    "tan boots",
  ]},
  { id: 39, time: "day", name: "Cinnamon Girl", vibe: "Warm Boho", items: [
    "burnt orange bralette top",
    "cream flowy linen pants",
    "straw hat",
    "layered gold necklaces",
    "cream sneakers",
  ]},
  { id: 40, time: "day", name: "Lake Day", vibe: "Swim Cover", items: [
    "white crochet bikini top",
    "white denim cutoffs",
    "straw lifeguard hat",
    "puka shell anklet",
    "white water shoes",
  ]},

  // ───────── SUNSET (41–70) — layered, golden hour glam ─────────
  { id: 41, time: "sunset", name: "Golden Hour Goddess", vibe: "Glam", items: [
    "sheer gold mesh long sleeve top",
    "rust satin flare pants",
    "gold body chain jewelry",
    "gold layered necklaces",
    "gold platform boots",
  ]},
  { id: 42, time: "sunset", name: "Flame Fairy", vibe: "Edgy Glam", items: [
    "orange sheer kimono",
    "black one piece bodysuit",
    "black flare pants",
    "gold statement earrings",
    "black platform sneakers",
  ]},
  { id: 43, time: "sunset", name: "Dusk Dream", vibe: "Ethereal", items: [
    "lavender sheer wrap top",
    "cream satin flare pants",
    "silver body jewelry",
    "face gems sticker",
    "cream platform boots",
  ]},
  { id: 44, time: "sunset", name: "Sunset Siren", vibe: "Velvet", items: [
    "rust velvet bodysuit",
    "cream wide leg pants",
    "gold coin belt",
    "chunky gold necklace",
    "gold ankle boots",
  ]},
  { id: 45, time: "sunset", name: "Magenta Magic", vibe: "Bold", items: [
    "magenta mesh long sleeve top",
    "black flare pants",
    "silver layered chain necklaces",
    "glitter face gems",
    "black platform boots",
  ]},
  { id: 46, time: "sunset", name: "Coral Queen", vibe: "Satin Glam", items: [
    "coral satin cami top",
    "high waist rust trousers",
    "gold body chain",
    "gold hoop earrings",
    "gold chunky sneakers",
  ]},
  { id: 47, time: "sunset", name: "Peach Haze", vibe: "Soft Dream", items: [
    "peach sheer kimono duster",
    "white seamless bodysuit",
    "rust flare pants",
    "pearl necklace",
    "cream platforms",
  ]},
  { id: 48, time: "sunset", name: "Mystic Rose", vibe: "Velvet Dark", items: [
    "rose velvet crop top",
    "black flare pants",
    "silver moon pendant necklace",
    "silver rings",
    "black platform boots",
  ]},
  { id: 49, time: "sunset", name: "Amber Glow", vibe: "Metallic", items: [
    "amber metallic crop top",
    "cream flare pants",
    "gold layered necklaces",
    "gold hoop earrings",
    "gold platform sneakers",
  ]},
  { id: 50, time: "sunset", name: "Lavender Haze", vibe: "Lace", items: [
    "lavender lace crop top",
    "cream flare jeans",
    "silver chain necklaces",
    "silver rings",
    "white platform sneakers",
  ]},
  { id: 51, time: "sunset", name: "Rust Revival", vibe: "Western Glam", items: [
    "rust satin cami top",
    "brown leather mini skirt",
    "gold braided belt",
    "brown thigh high boots",
    "gold layered necklaces",
  ]},
  { id: 52, time: "sunset", name: "Bronze Babe", vibe: "Sparkle", items: [
    "bronze sequin crop top",
    "black flare pants",
    "bronze chandelier earrings",
    "bronze chain necklace",
    "black platform boots",
  ]},
  { id: 53, time: "sunset", name: "Golden Glow", vibe: "Metallic", items: [
    "gold metallic bodysuit",
    "cream wide leg pants",
    "gold body chain",
    "gold cuff bracelet",
    "gold chunky sneakers",
  ]},
  { id: 54, time: "sunset", name: "Fire Starter", vibe: "Rock", items: [
    "red mesh long sleeve top",
    "black faux leather pants",
    "silver chain belt",
    "silver layered necklaces",
    "black combat boots",
  ]},
  { id: 55, time: "sunset", name: "Copper Dream", vibe: "Warm Retro", items: [
    "copper crop top",
    "rust corduroy wide leg pants",
    "gold hoops",
    "gold layered necklaces",
    "tan platform boots",
  ]},
  { id: 56, time: "sunset", name: "Velvet Rose", vibe: "Romantic", items: [
    "rose velvet cami top",
    "burgundy flare pants",
    "gold locket necklace",
    "gold rings",
    "burgundy platform boots",
  ]},
  { id: 57, time: "sunset", name: "Lilac Sky", vibe: "Soft", items: [
    "lilac silk cami",
    "cream flare pants",
    "silver chain necklace",
    "silver hoops",
    "white platforms",
  ]},
  { id: 58, time: "sunset", name: "Sunset Lace", vibe: "Lace Glam", items: [
    "coral lace crop top",
    "rust flare pants",
    "gold body chain",
    "gold layered necklaces",
    "cream platform boots",
  ]},
  { id: 59, time: "sunset", name: "Ember", vibe: "Dark Glam", items: [
    "burgundy mesh long sleeve",
    "black high waist flare jeans",
    "silver layered chains",
    "silver rings",
    "black platform boots",
  ]},
  { id: 60, time: "sunset", name: "Gilded", vibe: "Silk Glam", items: [
    "gold sequin cami top",
    "cream silk flare pants",
    "gold cuff bracelets",
    "gold earrings",
    "gold sneakers",
  ]},
  { id: 61, time: "sunset", name: "Desert Queen", vibe: "Leather", items: [
    "bronze halter top",
    "rust faux leather pants",
    "gold coin belt",
    "gold layered necklaces",
    "brown ankle boots",
  ]},
  { id: 62, time: "sunset", name: "Honey", vibe: "Wrap Glam", items: [
    "honey satin wrap top",
    "cream flare jeans",
    "gold layered necklaces",
    "gold hoops",
    "cream sneakers",
  ]},
  { id: 63, time: "sunset", name: "Tangerine", vibe: "Bright", items: [
    "orange satin cami",
    "white linen flare pants",
    "gold hoop earrings",
    "gold chain necklace",
    "white platform sneakers",
  ]},
  { id: 64, time: "sunset", name: "Rose Gold", vibe: "Pretty", items: [
    "rose gold metallic crop top",
    "cream faux leather pants",
    "rose gold jewelry set",
    "rose gold sneakers",
  ]},
  { id: 65, time: "sunset", name: "Dusty Pink", vibe: "Sheer", items: [
    "dusty pink sheer long sleeve top",
    "rust flare pants",
    "gold body chain",
    "gold necklaces",
    "gold platform boots",
  ]},
  { id: 66, time: "sunset", name: "Firelight", vibe: "Siren", items: [
    "red sheer kimono",
    "black seamless bodysuit",
    "black flare pants",
    "red statement lip",
    "black platform boots",
  ]},
  { id: 67, time: "sunset", name: "Moonstone", vibe: "Iridescent", items: [
    "iridescent crop top",
    "cream wide leg pants",
    "silver moon necklace",
    "silver body chain",
    "silver sneakers",
  ]},
  { id: 68, time: "sunset", name: "Velvet Dream", vibe: "Dark Velvet", items: [
    "burgundy velvet bodysuit",
    "black high waist flare jeans",
    "silver layered chains",
    "silver rings",
    "black platform boots",
  ]},
  { id: 69, time: "sunset", name: "Peach Glow", vibe: "Soft Glam", items: [
    "peach satin wrap top",
    "cream flare pants",
    "pearl jewelry set",
    "gold layered necklaces",
    "cream platform boots",
  ]},
  { id: 70, time: "sunset", name: "Sundown", vibe: "Mesh Warm", items: [
    "orange mesh crop top",
    "rust corduroy pants",
    "gold hoop earrings",
    "gold layered necklaces",
    "tan platform boots",
  ]},

  // ───────── NIGHT (71–100) — warm layers + funky ─────────
  { id: 71, time: "night", name: "Cozy Fairy", vibe: "Sherpa", items: [
    "cream oversized sherpa pullover",
    "rust seamless bodysuit",
    "black fleece lined leggings",
    "cream slouchy beanie",
    "platform combat boots women",
  ]},
  { id: 72, time: "night", name: "Fleece Goddess", vibe: "Warm Glam", items: [
    "rust fleece jacket women",
    "black mesh long sleeve bodysuit",
    "black flare pants",
    "black slouchy beanie",
    "black combat boots",
  ]},
  { id: 73, time: "night", name: "Puffer Queen", vibe: "Cropped", items: [
    "cream cropped puffer jacket",
    "mesh long sleeve top black",
    "black fleece lined leggings",
    "cream beanie",
    "white chunky sneakers",
  ]},
  { id: 74, time: "night", name: "Rave Creature", vibe: "LED", items: [
    "black sherpa pullover",
    "iridescent holographic bodysuit",
    "black leggings",
    "led gloving gloves",
    "black chunky sneakers",
  ]},
  { id: 75, time: "night", name: "Warm & Wild", vibe: "Earthy", items: [
    "olive fleece vest women",
    "rust long sleeve bodysuit",
    "black thermal leggings",
    "rust beanie",
    "combat boots women",
  ]},
  { id: 76, time: "night", name: "Nightshade", vibe: "Purple", items: [
    "black puffer jacket",
    "purple mesh bodysuit",
    "black leather leggings",
    "black beanie",
    "black chunky sneakers",
  ]},
  { id: 77, time: "night", name: "Golden Night", vibe: "Sparkle Warm", items: [
    "gold sequin crop top",
    "black cropped puffer jacket",
    "black fleece lined leggings",
    "gold statement earrings",
    "black platform boots",
  ]},
  { id: 78, time: "night", name: "Ember Night", vibe: "Burgundy", items: [
    "burgundy fleece pullover",
    "black mesh bodysuit",
    "black faux leather leggings",
    "black beanie",
    "black platform sneakers",
  ]},
  { id: 79, time: "night", name: "Sherpa Angel", vibe: "All Cream", items: [
    "cream sherpa jacket",
    "white seamless bodysuit",
    "cream fleece leggings",
    "cream beanie",
    "white platform sneakers",
  ]},
  { id: 80, time: "night", name: "Dust Warrior", vibe: "Utility", items: [
    "brown puffer vest",
    "black long sleeve thermal top",
    "black cargo pants women",
    "paisley bandana",
    "black combat boots",
  ]},
  { id: 81, time: "night", name: "LED Dream", vibe: "All White", items: [
    "white oversized sherpa",
    "white long sleeve bodysuit",
    "white fleece leggings",
    "fairy light hair clips",
    "white chunky sneakers",
  ]},
  { id: 82, time: "night", name: "Night Fairy", vibe: "Faux Fur", items: [
    "black velvet bodysuit",
    "cream faux fur jacket",
    "black leather leggings",
    "silver layered chains",
    "black platform boots",
  ]},
  { id: 83, time: "night", name: "Cosmic", vibe: "Purple Sherpa", items: [
    "purple sherpa pullover",
    "black seamless bodysuit",
    "black leggings",
    "iridescent hair clips",
    "black chunky sneakers",
  ]},
  { id: 84, time: "night", name: "Bonfire", vibe: "Rust Warm", items: [
    "rust sherpa jacket",
    "cream long sleeve bodysuit",
    "black fleece leggings",
    "cream beanie",
    "brown ankle boots",
  ]},
  { id: 85, time: "night", name: "Glacier", vibe: "Icy", items: [
    "white cropped puffer jacket",
    "silver metallic bodysuit",
    "white leggings",
    "white slouchy beanie",
    "white chunky sneakers",
  ]},
  { id: 86, time: "night", name: "Stardust", vibe: "Sparkle", items: [
    "black mesh long sleeve top",
    "silver sequin bralette",
    "black high waist flare pants",
    "silver face gems",
    "black platform boots",
  ]},
  { id: 87, time: "night", name: "Moonchild", vibe: "Cream Hoodie", items: [
    "cream oversized hoodie",
    "cream long sleeve bodysuit",
    "cream jogger sweatpants",
    "cream beanie",
    "cream chunky sneakers",
  ]},
  { id: 88, time: "night", name: "Chunky Knit", vibe: "Cozy", items: [
    "chunky knit cream sweater oversized",
    "black fleece lined leggings",
    "black ankle boots women",
    "cream beanie",
  ]},
  { id: 89, time: "night", name: "Night Rose", vibe: "Pink Puffer", items: [
    "rose pink puffer jacket",
    "black seamless bodysuit",
    "black faux leather pants",
    "black beanie",
    "black combat boots",
  ]},
  { id: 90, time: "night", name: "Midnight", vibe: "All Black", items: [
    "black sherpa pullover",
    "black mesh long sleeve top",
    "black flare pants",
    "black slouchy beanie",
    "black platform boots",
  ]},
  { id: 91, time: "night", name: "Amber Night", vibe: "Fleece Vest", items: [
    "amber fleece vest",
    "black long sleeve bodysuit",
    "black thermal leggings",
    "black beanie",
    "black chunky sneakers",
  ]},
  { id: 92, time: "night", name: "Velvet Night", vibe: "Catsuit", items: [
    "black velvet catsuit",
    "cream faux fur shawl",
    "silver layered chains",
    "silver statement earrings",
    "black platform boots",
  ]},
  { id: 93, time: "night", name: "Cloud", vibe: "Soft Pink", items: [
    "cream oversized hoodie",
    "white long sleeve bodysuit",
    "white fleece leggings",
    "white beanie",
    "white platform sneakers",
  ]},
  { id: 94, time: "night", name: "Shadow", vibe: "Black Utility", items: [
    "black oversized puffer coat",
    "black mesh bodysuit",
    "black cargo pants",
    "black slouchy beanie",
    "black combat boots",
  ]},
  { id: 95, time: "night", name: "Spark", vibe: "Red Sparkle", items: [
    "red sequin crop top",
    "black cropped puffer jacket",
    "black fleece lined leggings",
    "red statement lip",
    "black platform sneakers",
  ]},
  { id: 96, time: "night", name: "Sunset Night", vibe: "Corduroy", items: [
    "rust sherpa jacket women",
    "cream seamless bodysuit",
    "rust corduroy pants",
    "cream beanie",
    "tan ankle boots",
  ]},
  { id: 97, time: "night", name: "Warm Wanderer", vibe: "Olive", items: [
    "olive green puffer jacket",
    "black thermal long sleeve",
    "black fleece lined leggings",
    "olive beanie",
    "black combat boots",
  ]},
  { id: 98, time: "night", name: "Cosmic Fairy", vibe: "Holographic", items: [
    "holographic jacket women",
    "cream seamless bodysuit",
    "black leggings",
    "iridescent face gems",
    "white platform sneakers",
  ]},
  { id: 99, time: "night", name: "Fleece Fairy", vibe: "Pink Warm", items: [
    "pink fleece pullover oversized",
    "white long sleeve bodysuit",
    "white fleece leggings",
    "pink slouchy beanie",
    "white chunky sneakers",
  ]},
  { id: 100, time: "night", name: "Last Dance", vibe: "Mini Glam", items: [
    "gold sequin mini dress",
    "black cropped leather jacket",
    "black fleece lined leggings underneath",
    "gold statement earrings",
    "black platform boots",
  ]},
];

export const HIS_LOOKS = [
  { id: "h1", time: "day", name: "Canyon Cream", items: [
    "cream linen button down shirt men",
    "tan cargo shorts men",
    "cream bucket hat men",
    "goodr wraparound sunglasses",
    "white sneakers men",
  ]},
  { id: "h2", time: "day", name: "Desert Rust", items: [
    "rust oversized tshirt men",
    "olive cargo shorts men",
    "straw wide brim hat men",
    "pit viper sunglasses",
    "tan hiking sneakers men",
  ]},
  { id: "h3", time: "day", name: "Boho Traveler", items: [
    "beige linen short sleeve shirt",
    "cream linen pants men",
    "brown leather belt",
    "wire frame sunglasses",
    "brown leather sneakers",
  ]},
  { id: "h4", time: "sunset", name: "Golden Hour Guy", items: [
    "cream ribbed tank top men",
    "rust corduroy pants men",
    "gold chain necklace men",
    "tan canvas sneakers",
  ]},
  { id: "h5", time: "sunset", name: "Desert Cowboy", items: [
    "western denim shirt men",
    "brown leather belt",
    "black jeans men",
    "brown cowboy hat men",
    "brown boots men",
  ]},
  { id: "h6", time: "sunset", name: "Velvet Rust", items: [
    "rust velvet short sleeve button up",
    "black pants men",
    "gold chain",
    "black chelsea boots men",
  ]},
  { id: "h7", time: "night", name: "Sherpa Warm", items: [
    "cream sherpa pullover men",
    "black joggers men",
    "cream beanie men",
    "black combat boots men",
  ]},
  { id: "h8", time: "night", name: "Puffer Night", items: [
    "uniqlo ultra light down jacket men",
    "black long sleeve thermal men",
    "black cargo pants men",
    "black beanie men",
    "black sneakers men",
  ]},
  { id: "h9", time: "night", name: "Rust Fleece", items: [
    "rust fleece pullover men",
    "black thermal long sleeve men",
    "black joggers",
    "black beanie",
    "combat boots men",
  ]},
  { id: "h10", time: "night", name: "Camp Cozy", items: [
    "cream chunky knit sweater men",
    "black sweatpants men",
    "cream beanie",
    "brown boots men",
  ]},
];
